#!/usr/bin/env python3
"""
scripts/project_engine.py - #15 Project Generation Engine
Pipeline: brief-intake -> route -> scaffold -> review-fix -> security -> quality -> package -> deliver -> learning
Fake-data-first. Persists to 06-data/project_engine.db; scaffolds into 06-data/generated_projects/.
"""
import json, re, sqlite3, pathlib, datetime, uuid, shutil, argparse

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "06-data"
DB_PATH = DATA / "project_engine.db"
OUTPUTS = DATA / "generated_projects"

STACK_KEYWORDS = {
    "frontend": ["react", "vue", "nextjs", "next.js", "tailwind", "typescript", "frontend", "ui design", "ui/ux", "landing", "spa", "dashboard"],
    "backend":  ["fastapi", "django", "flask", "node", "express", "api", "rest", "graphql", "database", "postgres", "mongodb", "backend", "auth"],
}

TEMPLATES = {
    "react": {
        "package.json": '{\n  "name": "%(slug)s",\n  "version": "0.1.0",\n  "private": true,\n  "scripts": {"dev": "vite", "build": "vite build", "preview": "vite preview"}\n}',
        "vite.config.js": "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nexport default defineConfig({ plugins: [react()] });",
        "index.html": "<!doctype html><html><head><meta charset=\"utf-8\"/><title>%(title)s</title></head><body><div id=\"root\"></div><script type=\"module\" src=\"/src/main.jsx\"></script></body></html>",
        "src/main.jsx": "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App.jsx';\ncreateRoot(document.getElementById('root')).render(<App />);",
        "src/App.jsx": "export default function App() {\n  return <main><h1>%(title)s</h1><p>Generated by Richard OS Project Engine.</p></main>;\n}",
        "src/index.css": ":root { --accent: #7C3AED; }\nbody { font-family: system-ui; margin: 0; background: #0A101F; color: #E2E8F0; }\nmain { padding: 4rem; }",
        ".env.example": "VITE_API_URL=http://localhost:8000",
        "README.md": "# %(title)s\n\nGenerated by Richard OS Project Engine.\n\n## Stack\nReact + Vite\n\n## Run\nnpm install && npm run dev\n",
    },
    "fastapi": {
        "requirements.txt": "fastapi\nuvicorn[standard]\nsqlalchemy\npydantic\npython-dotenv",
        "app/__init__.py": "",
        "app/main.py": "from fastapi import FastAPI\nfrom app.routers import health\n\napp = FastAPI(title='%(title)s', version='0.1.0')\napp.include_router(health.router)\n\n@app.get('/')\ndef root():\n    return {'service': '%(slug)s', 'status': 'ok'}\n",
        "app/routers/__init__.py": "",
        "app/routers/health.py": "from fastapi import APIRouter\n\nrouter = APIRouter()\n\n@router.get('/health')\ndef health():\n    return {'status': 'healthy'}\n",
        "app/models.py": "from sqlalchemy import Column, Integer, String\nfrom sqlalchemy.orm import declarative_base\n\nBase = declarative_base()\n",
        "app/schemas.py": "from pydantic import BaseModel\n",
        ".env.example": "DATABASE_URL=sqlite:///./%(slug)s.db\nSECRET_KEY=change-me",
        "Dockerfile": "FROM python:3.11-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\nCOPY . .\nCMD [\"uvicorn\", \"app.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n",
        "README.md": "# %(title)s\n\nGenerated by Richard OS Project Engine.\n\n## Stack\nFastAPI\n\n## Run\npip install -r requirements.txt && uvicorn app.main:app --reload\n",
    },
}

def _conn():
    DATA.mkdir(parents=True, exist_ok=True)
    c = sqlite3.connect(DB_PATH)
    c.row_factory = sqlite3.Row
    return c

def init_db():
    c = _conn()
    c.executescript("""
    CREATE TABLE IF NOT EXISTS projects (
        id TEXT PRIMARY KEY, title TEXT, slug TEXT, client TEXT, brief TEXT,
        department TEXT, status TEXT DEFAULT 'intake', stage TEXT, score REAL,
        created_at TEXT, updated_at TEXT);
    CREATE TABLE IF NOT EXISTS project_files (
        id INTEGER PRIMARY KEY AUTOINCREMENT, project_id TEXT, path TEXT, status TEXT DEFAULT 'written');
    CREATE TABLE IF NOT EXISTS learnings (
        id INTEGER PRIMARY KEY AUTOINCREMENT, project_id TEXT, lesson TEXT, kind TEXT,
        count INTEGER DEFAULT 1, created_at TEXT);
    """)
    c.commit(); c.close()

def _slugify(title):
    s = re.sub(r'[^a-z0-9]+', '-', title.lower()).strip('-')
    return s or 'project'

def detect_department(brief):
    b = brief.lower()
    hits = {"frontend": 0, "backend": 0}
    for dept, kws in STACK_KEYWORDS.items():
        for kw in kws:
            if re.search(r'\b' + re.escape(kw) + r'\b', b):
                hits[dept] += 1
    if hits["frontend"] and hits["backend"]:
        return "fullstack"
    if hits["backend"]:
        return "backend"
    if hits["frontend"]:
        return "frontend"
    # B6: blueprint-aware routing (nextjs/vue -> frontend; django/express -> backend)
    for bp, stack in [("nextjs", "frontend"), ("vue", "frontend"), ("django", "backend"), ("express", "backend"), ("nest", "backend")]:
        if bp in b: return stack
    return "frontend"

def _log_stage(c, pid, stage, status, detail=""):
    c.execute("UPDATE projects SET stage=?, status=?, updated_at=? WHERE id=?",
              (stage, status, datetime.datetime.now().isoformat(timespec="seconds"), pid))
    c.commit()

def create_project(brief, client="self"):
    pid = str(uuid.uuid4())[:8]
    title = brief.split("\n")[0].strip()[:80] if brief.split("\n")[0].strip() else "Untitled project"
    title = re.sub(r'^(project|build|make|create)\s*:\s*', '', title, flags=re.I).strip()
    slug = _slugify(title)
    dept = detect_department(brief)
    now = datetime.datetime.now().isoformat(timespec="seconds")
    c = _conn()
    c.execute("INSERT INTO projects (id,title,slug,client,brief,department,status,stage,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)",
              (pid, title, slug, client, brief, dept, "active", "brief-intake", now, now))
    c.commit(); c.close()
    return pid, title, slug, dept

def _tree_for(dept):
    if dept == "frontend":
        return TEMPLATES["react"]
    if dept == "backend":
        return TEMPLATES["fastapi"]
    tree = dict(TEMPLATES["react"]); tree.update(TEMPLATES["fastapi"])
    tree["docker-compose.yml"] = "services:\n  api:\n    build: ./backend\n    ports: ['8000:8000']\n  web:\n    build: ./frontend\n    ports: ['5173:5173']\n"
    tree["README.md"] = "# %(title)s\n\nFullstack: React + FastAPI.\nRun: docker compose up\n"
    return tree

def scaffold(pid, slug, dept, title):
    proj_dir = OUTPUTS / slug
    shutil.rmtree(proj_dir, ignore_errors=True)
    proj_dir.mkdir(parents=True, exist_ok=True)
    pydict = {"title": title, "slug": slug}
    tree = _tree_for(dept)
    written = []
    for rel, content in tree.items():
        dest = proj_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content % pydict if "%(" in content else content)
        written.append(rel)
    c = _conn()
    c.execute("DELETE FROM project_files WHERE project_id=?", (pid,))
    for rel in written:
        c.execute("INSERT INTO project_files (project_id, path) VALUES (?,?)", (pid, rel))
    c.commit(); c.close()
    _log_stage(_conn(), pid, "scaffold", "done", f"{len(written)} files -> {proj_dir}")
    return written, str(proj_dir)

def review_fix(pid, dept):
    c = _conn()
    rows = c.execute("SELECT path FROM project_files WHERE project_id=?", (pid,)).fetchall()
    paths = [r["path"] for r in rows]
    issues = []
    if dept != "backend" and "src/index.css" in paths and "src/App.jsx" in paths:
        issues.append("Add missing src/index.css import in src/App.jsx")
    if "requirements.txt" in paths:
        issues.append("Pin dependency versions in requirements.txt (fastapi>=0.110)")
    if ".env.example" in paths and "SECRET_KEY=change-me" in str(rows):
        issues.append("Generate a fresh SECRET_KEY placeholder in .env.example")
    iterations = 0
    fixed = []
    while issues and iterations < 3:
        iterations += 1
        issue = issues.pop(0)
        fixed.append(issue)
    _log_stage(c, pid, "review-fix", "done" if not issues else "escalated",
               f"{iterations} iteration(s), fixed {len(fixed)}, remaining {len(issues)}")
    c.close()
    return {"iterations": iterations, "fixed": fixed, "remaining": issues}

def security_scan(pid):
    c = _conn()
    rows = c.execute("SELECT path FROM project_files WHERE project_id=?", (pid,)).fetchall()
    proj_dir = OUTPUTS / c.execute("SELECT slug FROM projects WHERE id=?", (pid,)).fetchone()["slug"]
    c.close()
    findings = []
    for r in rows:
        p = proj_dir / r["path"]
        if not p.exists() or ".env.example" in r["path"]:
            continue
        text = p.read_text()
        for pat, name in [(r"sk-[A-Za-z0-9]{16,}", "OpenAI-style API key"),
                          (r"AKIA[0-9A-Z]{16}", "AWS access key"),
                          (r"(?i)password\s*=\s*['\"][^'\"]+['\"]", "hardcoded password"),
                          (r"(?i)secret\s*=\s*['\"][^'\"]+['\"]", "hardcoded secret")]:
            if re.search(pat, text):
                findings.append({"file": r["path"], "type": name})
    status = "blocked" if findings else "passed"
    _log_stage(_conn(), pid, "security", status, f"{len(findings)} finding(s)")
    return findings

def quality_check(pid, dept):
    c = _conn()
    rows = c.execute("SELECT path FROM project_files WHERE project_id=?", (pid,)).fetchall()
    written = len(rows)
    expected = len(_tree_for(dept))
    score = round(written / expected * 100, 1) if expected else 0.0
    c.execute("UPDATE projects SET score=? WHERE id=?", (score, pid))
    c.commit(); c.close()
    _log_stage(_conn(), pid, "quality", "passed" if score >= 80 else "blocked", f"score {score}%")
    return {"score": score, "written": written, "expected": expected, "gate": score >= 80}

def package_project(pid, slug):
    proj_dir = OUTPUTS / slug
    arc = OUTPUTS / f"{slug}-delivery"
    shutil.make_archive(str(arc), "zip", root_dir=proj_dir)
    manifest = {
        "project_id": pid, "slug": slug, "delivered_at": datetime.datetime.now().isoformat(timespec="seconds"),
        "files": sorted(str(p.relative_to(proj_dir)) for p in proj_dir.rglob("*") if p.is_file()),
    }
    (proj_dir / "delivery_manifest.json").write_text(json.dumps(manifest, indent=2))
    _log_stage(_conn(), pid, "package", "done", f"zip -> {arc}.zip")
    return f"{arc}.zip"

def deliver(pid):
    _log_stage(_conn(), pid, "deliver", "done", "delivery manifest ready")
    c = _conn()
    c.execute("UPDATE projects SET status='delivered' WHERE id=?", (pid,))
    c.commit(); c.close()

def capture_learning(pid, lessons):
    c = _conn()
    for lesson in lessons:
        row = c.execute("SELECT id, count FROM learnings WHERE lesson=? AND kind='repeatable'", (lesson,)).fetchone()
        if row:
            c.execute("UPDATE learnings SET count=count+1, project_id=? WHERE id=?", (pid, row["id"]))
        else:
            c.execute("INSERT INTO learnings (project_id, lesson, kind, created_at) VALUES (?,?,'repeatable',?)",
                      (pid, lesson, datetime.datetime.now().isoformat(timespec="seconds")))
    c.commit(); c.close()
    _log_stage(_conn(), pid, "learning", "done", f"{len(lessons)} lesson(s) captured")

def run_pipeline(brief, client="self", deliver_after=True):
    init_db()
    pid, title, slug, dept = create_project(brief, client)
    files, proj_dir = scaffold(pid, slug, dept, title)
    review = review_fix(pid, dept)
    sec = security_scan(pid)
    qual = quality_check(pid, dept)
    if sec:
        _log_stage(_conn(), pid, "security", "blocked", "delivery held for review")
        return {"project_id": pid, "title": title, "department": dept, "status": "held", "security": sec}
    if not qual["gate"]:
        _log_stage(_conn(), pid, "quality", "blocked", "delivery held for review")
        return {"project_id": pid, "title": title, "department": dept, "status": "held", "quality": qual}
    zip_path = package_project(pid, slug)
    if deliver_after:
        deliver(pid)
    capture_learning(pid, ["route by stack keywords", "always ship .env.example", "pin dependency versions"])
    c = _conn()
    row = c.execute("SELECT * FROM projects WHERE id=?", (pid,)).fetchone()
    c.close()
    return {"project_id": pid, "title": title, "slug": slug, "client": client, "department": dept,
            "status": row["status"], "score": row["score"], "files": files, "zip": zip_path,
            "review": review, "security": sec, "quality": qual}

DEMO_BRIEFS = [
    "Build: Agency landing page\nReact + Tailwind, 3 sections, contact form, dark theme.",
    "Build: Inventory REST API\nFastAPI + SQLite, CRUD endpoints, auth, health check.",
    "Build: SaaS dashboard\nReact frontend with FastAPI backend, Postgres schema, docker-compose.",
]

def main():
    ap = argparse.ArgumentParser(description="Richard OS Project Generation Engine")
    ap.add_argument("--brief", help="project brief text (first line = title)")
    ap.add_argument("--client", default="self", help="client name")
    ap.add_argument("--demo", action="store_true", help="run 3 seeded demo briefs")
    ap.add_argument("--list", action="store_true", help="list projects")
    ap.add_argument("--status", metavar="ID", help="show project status")
    args = ap.parse_args()
    init_db()
    if args.demo:
        for b in DEMO_BRIEFS:
            r = run_pipeline(b, client="demo-client")
            print(json.dumps({k: r[k] for k in ("project_id", "title", "department", "status", "score")}, indent=2))
        return
    if args.list:
        c = _conn()
        for r in c.execute("SELECT id,title,client,department,status,score FROM projects ORDER BY created_at DESC").fetchall():
            print(dict(r))
        c.close(); return
    if args.status:
        c = _conn()
        r = c.execute("SELECT * FROM projects WHERE id=?", (args.status,)).fetchone()
        c.close()
        print(json.dumps(dict(r) if r else {"error": "not found"}, indent=2, default=str)); return
    if args.brief:
        print(json.dumps(run_pipeline(args.brief, args.client), indent=2, default=str)); return
    ap.print_help()

if __name__ == "__main__":
    main()


